<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
<PropertyGroup>
  <AssemblyName>LitteraCore</AssemblyName>
  <OutputType>Exe</OutputType>
  <UseAppHost>true</UseAppHost>
</PropertyGroup>
  <ItemGroup>
    <Compile Remove="DBContext\BaseRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.14.0" />
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.36" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
    <PackageReference Include="Microsoft.PowerBI.Api" Version="4.22.0" />
    <PackageReference Include="MimeKit" Version="4.8.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="IRepository\" />
    <Folder Include="logs\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="YEncryptDecryptData">
      <HintPath>dlllib\YEncryptDecryptData.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
